# lmfao

default_max_body_size = "123"

[[server]]
host = "127.0.0.1" 
port = [12, -123]
server_name = ["example.com"] 
max_body_size = "23"

[[server.error_pages]]
404 = "404.html"
505 = "505.html"
400 = "400.html"

[[server.route]]
path = "/api/v1"
methods = ["GET"]
autoindex = true
