# lmfao

default_max_body_size = "123"

[[server]]
host="123.0.0.0"
port = [12, 123]
server_name = ["example.com"] 
max_body_size = "1000000"

[[server.error_pages]]
404 = "404.html"
505 = "505.html"
400 = "400.html"

[[server.route]]
locatoin = "imgs"
methods = ["GET"]
autoindex = true
index = "index.html"
root = "/var/www/html/pepe/"
