# weqeq2eqwewqe
# 
[[server]]
[[server.location]] # eqweqweq
path = "/"
root = "/var/www/html"
root = "/var/www/html"
methods = ["GET", "POST"]
autoindex = true
port = 8080
table = { key1 = "value1", key2 = "value2" }
[[server.pepe.end]]
key=13
[[server]]
host = "0.0.0.0"
port = 9090 

[["server.location"]]

path = "/"
methods = ["GET"]
autoindex = false
[[eqe]]