     
port = 8080
[[server-location]]
path = "/"
root = "/var/www/html"
root = "/var/www/html"
methods = ["GET", "POST"]
autoindex = true
[[server]]
host = "0.0.0.0"
port = 9090

[["server.location"]]

path = "/"
methods = ["GET"]
autoindex = false
table = {420 = "./qwere", '12'we= "123a}
